// frontend/src/lib/AppCard.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { AppInfo } from '../types/app';
  
  export let app: AppInfo;
  
  const dispatch = createEventDispatcher<{
    launch: string;
    toggleFavorite: string;
  }>();
  
  function handleLaunch() {
    dispatch('launch', app.exec);
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      handleLaunch();
    }
  }
  
  function handleToggleFavorite(event: Event) {
    event.stopPropagation();
    dispatch('toggleFavorite', app.name);
  }
</script>

<div 
  on:click={handleLaunch} 
  on:keydown={handleKeydown} 
  role="button" 
  tabindex="0"
  class="border transition-all duration-200 cursor-pointer focus:outline-none focus:ring-2 focus:ring-opacity-50"
  style="border-radius: 16px; padding: 12px; background-color: var(--color-card-background); border-color: var(--color-border);"
>
  <div class="flex items-start justify-between mb-1">
    <h3 class="text-sm font-medium truncate">{app.name}</h3>
    <button
      type="button"
      on:click={handleToggleFavorite}
      aria-label="{app.isFavorite ? 'Remove from favorites' : 'Add to favorites'}"
      class="flex-shrink-0 ml-1 p-0.5 transition-colors duration-200"
    >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" style="color: {app.isFavorite ? 'var(--color-accent-orange)' : 'var(--color-secondary-text)'};">
        <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
      </svg>
    </button>
  </div>
  
  {#if app.comment}
    <p class="text-xs mb-1 line-clamp-1" style="color: var(--color-secondary-text);">{app.comment}</p>
  {/if}
  
  {#if app.categories}
    <div class="flex flex-wrap gap-1 mb-1">
      {#each app.categories.split(';').slice(0, 2) as category}
        {#if category.trim()}
          <span class="inline-block px-1.5 py-0.5 text-xs font-medium rounded border" style="background-color: #21262d; color: var(--color-primary-text); border-color: var(--color-border);">{category.trim()}</span>
        {/if}
      {/each}
    </div>
  {/if}
  
  <p class="text-xs text-[#a855f7] font-mono truncate">{app.exec}</p>
</div>

// frontend/src/components/AppCard.vue
<template>
  <div class="app-card group" @click="handleLaunch">
    <div class="flex items-start space-x-3">
      <!-- App Icon -->
      <div class="flex-shrink-0">
        <div class="w-12 h-12 bg-gradient-to-br from-primary-500 to-primary-600 rounded-lg flex items-center justify-center text-white font-semibold text-lg">
          {{ appIcon }}
        </div>
      </div>
      
      <!-- App Info -->
      <div class="flex-1 min-w-0">
        <div class="flex items-start justify-between">
          <div class="flex-1 min-w-0">
            <h3 class="text-sm font-medium text-gray-900 dark:text-white truncate">
              {{ app.displayName || app.name }}
            </h3>
            <p v-if="app.description" class="text-xs text-gray-500 dark:text-gray-400 mt-1 line-clamp-2">
              {{ app.description }}
            </p>
            <div class="flex items-center space-x-2 mt-2">
              <span v-if="app.useCount > 0" class="text-xs text-gray-400 dark:text-gray-500">
                Used {{ app.useCount }} times
              </span>
              <span v-if="app.categories && app.categories.length > 0" class="text-xs text-gray-400 dark:text-gray-500">
                {{ app.categories[0] }}
              </span>
            </div>
          </div>
          
          <!-- Favorite Button -->
          <button
            @click.stop="handleToggleFavorite"
            class="flex-shrink-0 p-1 text-gray-400 hover:text-yellow-500 transition-colors duration-200 opacity-0 group-hover:opacity-100"
            :class="{ 'text-yellow-500 opacity-100': app.isFavorite }"
          >
            <StarIcon class="w-4 h-4" :fill="app.isFavorite ? 'currentColor' : 'none'" />
          </button>
        </div>
      </div>
    </div>
    
    <!-- Hover Actions -->
    <div class="absolute inset-0 bg-primary-600 bg-opacity-0 group-hover:bg-opacity-5 transition-all duration-200 rounded-lg flex items-center justify-center opacity-0 group-hover:opacity-100">
      <div class="flex items-center space-x-2">
        <button
          @click.stop="handleLaunch"
          class="btn-primary text-sm px-3 py-1"
        >
          Launch
        </button>
        <button
          @click.stop="handleToggleFavorite"
          class="btn-secondary text-sm px-3 py-1"
        >
          {{ app.isFavorite ? 'Unfavorite' : 'Favorite' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import { computed } from 'vue'
import { StarIcon } from 'lucide-vue-next'

export default {
  name: 'AppCard',
  components: {
    StarIcon
  },
  props: {
    app: {
      type: Object,
      required: true
    }
  },
  emits: ['launch', 'toggle-favorite'],
  setup(props, { emit }) {
    const appIcon = computed(() => {
      const name = props.app.displayName || props.app.name
      if (!name) return '?'
      
      // Get first letter of each word, up to 2 characters
      const words = name.split(' ')
      if (words.length >= 2) {
        return (words[0][0] + words[1][0]).toUpperCase()
      }
      return name[0].toUpperCase()
    })

    const handleLaunch = () => {
      emit('launch', props.app.id)
    }

    const handleToggleFavorite = () => {
      emit('toggle-favorite', props.app.id)
    }

    return {
      appIcon,
      handleLaunch,
      handleToggleFavorite
    }
  }
}
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
